language: android
jdk: oraclejdk8
sudo: false
android:
    components:
        - tools
        - build-tools-25.0.0
        - android-25
        - extra-android-support
        - extra-android-m2repository

script:
- ./gradlew clean build
